version 1.2.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -118,8 +118,14 @@ OMP
 	for flag in "" "-fopenmp" "-fopenmp=libomp" "-openmp" "-xopenmp" "-mp"; do
 		$CC $CFLAGS $flag -c $tmpdir/openmp.c -o $tmpdir/openmp.o 2> /dev/null
 		if [ $? -eq 0 ]; then
-			echo $flag
-			return
+			$CC $LDFLAGS $flag $tmpdir/openmp.o -o $tmpdir/openmp 2> /dev/null
+			if [ $? -eq 0 ]; then
+				echo $flag
+				return
+			else
+				echo "CANNOT_LINK"
+				return
+			fi
 		fi
 	done
 	echo "NOT_FOUND"
@@ -184,15 +190,19 @@ at_sed_replacement() {
 #
 
 # These are fixed
-PROFIT_VERSION=`cat src/libprofit/VERSION`
 PROFIT_USES_R=yes
 PROFIT_USES_GSL=no
 PROFIT_DEBUG=no
 
 # These are actually modified by this script
+PROFIT_VERSION_MAJOR=
+PROFIT_VERSION_MINOR=
+PROFIT_VERSION_PATCH=
+PROFIT_VERSION_SUFFIX=
 PROFIT_OPENCL=no
 PROFIT_OPENCL_MAJOR=
 PROFIT_OPENCL_MINOR=
+PROFIT_OPENCL_TARGET_VERSION=
 PROFIT_OPENMP=no
 PROFIT_FFTW=no
 PROFIT_FFTW_OPENMP=no
@@ -211,7 +221,10 @@ generate_makevars() {
 }
 
 generate_config_h() {
-	sexpr="`at_sed_replacement PROFIT_VERSION`"
+	sexpr="`at_sed_replacement PROFIT_VERSION_MAJOR`"
+	sexpr="$sexpr; `at_sed_replacement PROFIT_VERSION_MINOR`"
+	sexpr="$sexpr; `at_sed_replacement PROFIT_VERSION_PATCH`"
+	sexpr="$sexpr; `at_sed_replacement PROFIT_VERSION_SUFFIX`"
 	sexpr="$sexpr; `cmakedefine_sed_replacement PROFIT_USES_R`"
 	sexpr="$sexpr; `cmakedefine_sed_replacement PROFIT_USES_GSL`"
 	sexpr="$sexpr; `cmakedefine_sed_replacement PROFIT_DEBUG`"
@@ -221,6 +234,7 @@ generate_config_h() {
 	sexpr="$sexpr; `cmakedefine_sed_replacement PROFIT_FFTW_OPENMP`"
 	sexpr="$sexpr; `at_sed_replacement PROFIT_OPENCL_MAJOR`"
 	sexpr="$sexpr; `at_sed_replacement PROFIT_OPENCL_MINOR`"
+	sexpr="$sexpr; `at_sed_replacement PROFIT_OPENCL_TARGET_VERSION`"
 	generate_file src/libprofit/profit/config.h "$sexpr"
 }
 
@@ -230,6 +244,22 @@ generate_config_h() {
 detect_system
 tmpdir=.profit_tmp
 [ -d $tmpdir ] || mkdir $tmpdir || { echo "couldn't create temporary directory $tmpdir" && exit 1; }
+
+#
+# Calculate the version components
+#
+version=`cat src/libprofit/VERSION`
+echo "- Compiling Profit using libprofit $version"
+PROFIT_VERSION_MAJOR=${version%%.*}
+version=${version#*.}
+PROFIT_VERSION_MINOR=${version%%.*}
+version=${version#*.}
+PROFIT_VERSION_PATCH=${version%%-*}
+version_without_dash=${version#*-}
+if [ "$version" != "${version_without_dash}" ]
+then
+	PROFIT_VERSION_SUFFIX=${version_without_dash}
+fi
 
 #
 # Check for OpenCL headers, libs and max OpenCL version
@@ -257,6 +287,14 @@ else
 		PROFIT_OPENCL_MAJOR=${cl_ver_maj}
 		PROFIT_OPENCL_MINOR=${cl_ver_min}
 		cl_libflags=`get_cl_libflags`
+		PROFIT_OPENCL_TARGET_VERSION=110
+
+		# In OSX 10.8 (Darwin 12.0) the Apple OpenCL platform was already 1.2,
+		# and trying to compile with a target version of 1.1
+		# (depending on the compiler) generates lots of deprecation warnings
+		if [ "$OS" = "Darwin" -a "`uname -r`" \> "12" ]; then
+			PROFIT_OPENCL_TARGET_VERSION=120
+		fi
 	else
 		echo "- Compiling without OpenCL support"
 	fi
@@ -271,13 +309,27 @@ if [ -n "${PROFIT_NO_OPENMP}" ]; then
 	echo "- Skipping OpenMP detection"
 else
 	omp_flag=`get_omp_cflag`
-	if [ "$omp_flag" != "NOT_FOUND" ]; then
+	if [ "$omp_flag" = "NOT_FOUND" ]; then
+		echo "- Compiling without OpenMP support"
+	elif [ "$omp_flag" = "CANNOT_LINK" ]; then
+		echo ""
+		echo "################################################################################"
+		echo " Using the OpenMP compilation flag '$flag' your compiler is able to *compile*"
+		echo " code using OpenMP, but it still fails to *link* (i.e., produce a library or an"
+		echo " executable)."
+		echo " This possibly indicates either a faulty installation of your compiler, of your"
+		echo " OpenMP library, or a missing dependency for the OpenMP library."
+		echo ""
+		echo " Since we cannot use '$flag' to provide a working compilation process, we will"
+		echo " compile ProFit without OpenMP support"
+		echo "################################################################################"
+		echo ""
+		break
+	else
 		echo "- Compiling with OpenMP support"
 		PROFIT_OPENMP=yes
 		omp_cflags="$omp_flag"
 		omp_libflags="$omp_flag"
-	else
-		echo "- Compiling without OpenMP support"
 	fi
 
 fi
